version: 2

defaults: &defaults
  working_directory: ~/qlik-word-cloud
  docker:
    - image: circleci/node:stretch-browsers
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "br.com.clever.wordcloud"
    PACKAGE_NAME: "qlik-word-cloud"

jobs:
  bump-version:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Bump version
          command: scripts/bump-version.sh $GITHUB_ORG $GITHUB_REPO
      - persist_to_workspace:
          root: ~/qlik-word-cloud
          paths:
            - BUMPED_VERSION

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-word-cloud
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and package
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            npm run build
          environment:
            NODE_ENV: production
      - run:
          name: BlackDuck scan
          command: curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh | bash -s -- \
            --blackduck.url="https://qliktech.blackducksoftware.com" \
            --blackduck.trust.cert=true \
            --blackduck.username="svc-blackduck" \
            --blackduck.password=${svc_blackduck} \
            --detect.project.name="viz-bundle-qlik-word-cloud"
      - persist_to_workspace:
          root: ~/qlik-word-cloud
          paths:
            - build
      - store_artifacts:
          path: build
          destination: build
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-word-cloud
      - run:
          name: Install ghr
          command: scripts/install-ghr.sh
      - run:
          name: Create GitHub Release
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            scripts/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME $VERSION

workflows:
  version: 2
  master_flow:
    jobs:
      - bump-version
      - build:
          requires:
            - bump-version
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
